CREATE USER interview WITH PASSWORD 'xxx';
ALTER ROLE interview WITH SUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;

CREATE DATABASE interviewdb
    WITH
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

ALTER DATABASE interviewdb owner to interview;
